#!/usr/bin/env python3
"""Promote a reviewed shared-memory candidate and atomically update approval metadata."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from scan_memory import (
    ALLOWED_TYPES,
    DEFAULT_RULES,
    ENTRY_NAME_RE,
    REPO_ROOT,
    SEVERITY_RANK,
    digest_memory_file,
    load_rules,
    parse_memory_frontmatter,
    scan_memory_entry,
    verify_registry,
)


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("entry", help="candidate memory entry name (filename stem, lowercase snake_case)")
    result.add_argument("--approved-by", required=True, help="human reviewer identity")
    result.add_argument("--source", required=True, help="reviewed source, e.g. a machine, user, or session identifier")
    result.add_argument("--review-note", required=True, help="what the human reviewer checked")
    result.add_argument("--accept-risk", action="append", default=[], metavar="RULE_ID", help="explicitly accept one medium-risk rule ID")
    result.add_argument("--apply", action="store_true", help="apply the promotion; omission is a dry run")
    result.add_argument("--replace", action="store_true", help="replace an existing approved memory entry and retain its registry history")
    result.add_argument("--root", type=Path, default=REPO_ROOT, help=argparse.SUPPRESS)
    return result


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(handle, "w", encoding="utf-8") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp_name, path)
    except Exception:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass
        raise


def atomic_json_write(path: Path, payload: dict) -> None:
    atomic_write(path, json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n")


def render_index(registry: dict) -> str:
    lines = [
        "# Shared memory index",
        "",
        "Generated by the governance scripts. Do not edit by hand.",
        "",
        "Every governed Claude session must verify this index and read `standard_load.md` at session start.",
        "Load other approved entries only when the task needs them. Always read the current repository copies; never",
        "load candidate memory as context. These entries do not authorize unrelated actions. See `rules/policy.md`.",
        "",
    ]
    entries: dict = registry.get("entries", {})
    for name in sorted(entries):
        entry = entries[name]
        if entry.get("status") != "approved":
            continue
        description = entry.get("description", "")
        memory_type = entry.get("memory_type", "")
        lines.append(f"- [{name}]({name}.md) — {description} ({memory_type})")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = parser().parse_args(argv)
    root = args.root.resolve()
    name = args.entry
    if not ENTRY_NAME_RE.fullmatch(name) or len(name) > 64:
        print("ERROR: entry name must be lowercase snake_case and at most 64 characters", file=sys.stderr)
        return 2
    if not args.approved_by.strip() or not args.source.strip() or not args.review_note.strip():
        print("ERROR: approval identity, source, and review note cannot be blank", file=sys.stderr)
        return 2

    candidate = root / "memory" / "candidates" / f"{name}.md"
    approved = root / "memory" / "approved" / f"{name}.md"
    registry_path = root / "registry" / "approved-memory.json"
    if not candidate.is_file() or candidate.is_symlink():
        print(f"ERROR: candidate memory file does not exist as a regular file: {candidate}", file=sys.stderr)
        return 2
    if approved.exists() and not args.replace:
        print("ERROR: approved memory entry already exists; use --replace for an explicitly reviewed update", file=sys.stderr)
        return 2
    if args.replace and not approved.is_file():
        print("ERROR: --replace requires an existing approved memory entry", file=sys.stderr)
        return 2

    rules = load_rules(DEFAULT_RULES if root == REPO_ROOT else root / "rules" / "scanning-rules.json")
    integrity_findings = verify_registry(root, rules, name)
    if integrity_findings:
        for item in integrity_findings:
            print(f"{item.severity.upper()} {item.rule_id} {item.path}: {item.message}", file=sys.stderr)
        print("ERROR: existing approval state is inconsistent; repair it in a separate reviewed change", file=sys.stderr)
        return 2

    findings = scan_memory_entry(candidate, rules, root)
    blockers = [item for item in findings if SEVERITY_RANK[item.severity] >= SEVERITY_RANK["high"]]
    medium_ids = {item.rule_id for item in findings if item.severity == "medium"}
    accepted = set(args.accept_risk)
    missing_acceptance = medium_ids - accepted
    unknown_acceptance = accepted - medium_ids
    if blockers:
        for item in blockers:
            print(f"{item.severity.upper()} {item.rule_id} {item.path}: {item.message}", file=sys.stderr)
        print("ERROR: critical and high findings cannot be promoted", file=sys.stderr)
        return 1
    if missing_acceptance:
        print(f"ERROR: medium findings require --accept-risk for: {', '.join(sorted(missing_acceptance))}", file=sys.stderr)
        return 1
    if unknown_acceptance:
        print(f"ERROR: accepted risk IDs not present in the scan: {', '.join(sorted(unknown_acceptance))}", file=sys.stderr)
        return 2

    metadata, memory_type, fm_errors = parse_memory_frontmatter(candidate.read_text(encoding="utf-8"), rules["limits"]["max_frontmatter_lines"])
    if fm_errors or not metadata.get("description") or memory_type not in ALLOWED_TYPES:
        print("ERROR: cannot promote invalid frontmatter", file=sys.stderr)
        return 2

    candidate_digest = digest_memory_file(candidate)
    print(f"Candidate: {name}")
    print(f"Digest:    {candidate_digest}")
    print(f"Type:      {memory_type}")
    print(f"Findings:  {len(findings)} ({len(medium_ids)} accepted medium-risk rule IDs)")
    print(f"Action:    {'replace' if args.replace else 'promote'}")
    if not args.apply:
        print("DRY RUN: no files changed; repeat with --apply only after explicit human approval")
        return 0

    try:
        registry = json.loads(registry_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        print(f"ERROR: cannot read registry: {exc}", file=sys.stderr)
        return 2
    if registry.get("schema_version") != 1 or not isinstance(registry.get("entries"), dict):
        print("ERROR: invalid registry schema", file=sys.stderr)
        return 2

    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    previous = registry["entries"].get(name)
    history = list(previous.get("history", [])) if isinstance(previous, dict) else []
    if previous:
        history.append({key: previous.get(key) for key in ("approved_at", "approved_by", "digest", "source", "review_note", "accepted_risks", "memory_type")})
    entry = {
        "status": "approved",
        "digest": candidate_digest,
        "memory_type": memory_type,
        "description": metadata.get("description", ""),
        "approved_at": now,
        "approved_by": [args.approved_by.strip()],
        "source": args.source.strip(),
        "review_note": args.review_note.strip(),
        "accepted_risks": sorted(accepted),
        "scan_findings": [
            {"rule_id": item.rule_id, "severity": item.severity, "path": item.path, "line": item.line}
            for item in findings
        ],
        "history": history,
    }

    approved.parent.mkdir(parents=True, exist_ok=True)
    backup = approved.parent / f".{name}.md.backup"
    consumed_candidate = candidate.parent / f".{name}.promoted"
    committed = False
    backed_up = False
    candidate_consumed = False
    try:
        if backup.exists() or consumed_candidate.exists():
            raise RuntimeError("stale promotion backup blocks promotion")
        handle, temp_name = tempfile.mkstemp(prefix=f".{name}.md.", suffix=".tmp", dir=approved.parent)
        os.close(handle)
        try:
            shutil.copy2(candidate, temp_name)
            if digest_memory_file(Path(temp_name)) != candidate_digest:
                raise RuntimeError("staged copy digest differs from reviewed candidate")
            if approved.exists():
                os.replace(approved, backup)
                backed_up = True
            os.replace(temp_name, approved)
        except Exception:
            if os.path.exists(temp_name):
                os.unlink(temp_name)
            raise
        os.replace(candidate, consumed_candidate)
        candidate_consumed = True
        registry["entries"][name] = entry
        atomic_json_write(registry_path, registry)
        atomic_write(approved.parent / "MEMORY.md", render_index(registry))
        committed = True
    except Exception as exc:
        if not committed:
            if approved.exists():
                approved.unlink()
            if backed_up and backup.exists():
                os.replace(backup, approved)
            if candidate_consumed and consumed_candidate.exists():
                os.replace(consumed_candidate, candidate)
        print(f"ERROR: promotion failed and rollback was attempted: {exc}", file=sys.stderr)
        return 2

    if backup.exists():
        try:
            backup.unlink()
        except OSError as exc:
            print(f"WARNING: promotion succeeded but old backup remains at {backup}: {exc}", file=sys.stderr)

    if consumed_candidate.exists():
        try:
            consumed_candidate.unlink()
        except OSError as exc:
            print(f"WARNING: promotion succeeded but consumed candidate remains at {consumed_candidate}: {exc}", file=sys.stderr)

    print("APPLIED: approved memory entry, shared index, and registry updated; candidate consumed")
    print("NEXT: run unit tests and python3 scripts/scan_memory.py --scope all")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
